image: "openjdk:8"

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - ".gradle/caches"

before_script:
  - "mkdir -p $(pwd)/.gradle"
  - "export GRADLE_USER_HOME=$(pwd)/.gradle"
  - "echo $SIGNING_properties | base64 -d > .gradle/gradle.properties"
  - "echo $SIGNING_secretKey | base64 -d > .gradle/sonatype_upload.gpg"
  - "chmod +x ./gradlew"

stages:
  - "build"
  - "test"
  - "release"

build:
  stage: "build"
  script:
    - "./gradlew build"
  rules:
    - if: "$CI_COMMIT_BRANCH == 'main'"
      when: on_success

test:
  stage: "test"
  script:
    - "./gradlew check --stacktrace"
  artifacts:
    paths:
      - "build/test-results/**/TEST-*.xml"
    reports:
      junit:
        - "build/test-results/**/TEST-*.xml"
  rules:
    - if: "$CI_COMMIT_BRANCH == 'main'"
      when: on_success
  dependencies:
    - "build"

release:
  stage: "release"
  cache: {}
  script:
    - "./gradlew publish"
  artifacts:
    paths:
      - "build/libs/*"
  dependencies:
    - "build"
    - "test"
  rules:
    - if: "$CI_COMMIT_TAG != '' && $CI_COMMIT_BRANCH == 'main'"
      when: on_success
